version: "3"

services:
  auth_fpm1:
    image: infomir/fpm:7.1
    volumes:
      - ./:/home/infomir
    environment:
      XDEBUG_REMOTE_HOST: ${REAL_IP}
      XDEBUG_ENABLE: 1
      PROJECT_DIR_ROOT: /home/infomir/src
      PROJECT_NAME: auth-bundle
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      auth-net:
        aliases:
          - auth_fpm1

  nginx:
    image: sonrac/infomir-nginx
    volumes:
     - ./:/home/infomir
    depends_on:
      - auth_fpm1
    environment:
      PROJECT_DIR_ROOT: /home/infomir/src
      PUBLIC_PATH: /home/infomir/tests/app/public
      FPM_SERVER: auth_fpm1
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.auth.api.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.auth.api.docker.network=auth-net"
        - "traefik.auth.api.frontend.rule=Host:auth.devinf"
        - "traefik.auth.api.backend=auth"
        - "traefik.auth.api.port=80"
    networks:
      traefik-net:
      auth-net:
        aliases:
          - auth_nginx

networks:
  traefik-net:
    external: true
  auth-net:
    driver: overlay
