parameters:
  sonrac_auth.client.provider.class: sonrac\Auth\Providers\ClientProvider
  sonrac_auth.user.provider.class: sonrac\Auth\Providers\UserProvider

sonrac_auth:
  encryption_key:
  private_key_path: '%kernel.project_dir%/resources/keys'
  pass_phrase:
  password_salt:
  access_token_lifetime: 3600
  refresh_token_lifetime: 3600
  auth_code_lifetime: 3600
  query_delimiter: "?"
  header_token_name: "API-TOKEN"
  enable_grant_types:
    client_credentials: true
    password: true
    refresh_token: true
    authorization_code: true
    implicit: true
  swagger_constants:
    url: ~
  default_scopes:
    - default

services:
  sonrac.oauth.generate_client:
    class: sonrac\Auth\Command\GenerateClient
    tags: ['sonrac.oauth.commands', 'console.command']
  sonrac.oauth.generate_keys:
    class: sonrac\Auth\Command\GenerateKeys
    tags: ['sonrac.oauth.commands', 'console.command']
  sonrac.oauth.clear_tokens:
    class: sonrac\Auth\Command\ClearTokens
    tags: ['sonrac.oauth.commands', 'console.command']
  sonrac_auth.client_provider:
    class: '%sonrac_auth.client.provider.class%'
    arguments:
      - '@League\OAuth2\Server\Repositories\ClientRepositoryInterface'
      - '@doctrine.orm.default_entity_manager'
  sonrac_auth.oauth2_authenticator:
    class: sonrac\Auth\Security\OAuth2Authenticator
    arguments:
      - '%sonrac_auth.header_token_name%'
  sonrac_auth.user_provider:
    class: '%sonrac_auth.user.provider.class%'
    arguments:
      - '@League\OAuth2\Server\Repositories\UserRepositoryInterface'
