parameters:

sonrac_auth:
  encryption_key:
  private_key_path: '%kernel.project_dir%/resources/keys'
  pass_phrase:
  password_salt:
  access_token_lifetime: 3600
  refresh_token_lifetime: 3600
  auth_code_lifetime: 3600
  query_delimiter: "#"
  enable_grant_types:
    clientCredentials: true
    password: true
    refreshToken: true
    code: true
    implicit: true

services:
  sonrac.oauth.generate_client:
    class: sonrac\Auth\Command\GenerateClient
    tags: ['sonrac.oauth.commands', 'console.command']
  sonrac.oauth.generate_keys:
    class: sonrac\Auth\Command\GenerateKeys
    tags: ['sonrac.oauth.commands', 'console.command']
  sonrac.oauth.clear_tokens:
    class: sonrac\Auth\Command\ClearTokens
    tags: ['sonrac.oauth.commands', 'console.command']
