sonrac\Entity\Client:
  table: access_tokens
  repositoryClass: sonrac\Repository\Clients
  type: entity
  id:
    name:
      type: string

  fields:
    name:
      type: string
      nullable: false
      length: 255
    token_scopes:
      type: string
      nullable: false
      length: 5000
    user_id:
      type: integer
      nullable: false
    client_id:
      type: integer
      nullable: true
    expire_at:
      type: integer
      length: 20
      nullable: false
    created_at:
      type: integer
      length: 20
      nullable: false
    updated_at:
      type: integer
      length: 20
      nullable: false
