sonrac\Auth\Entity\AccessToken:
  table: access_tokens
  repositoryClass: sonrac\Repository\AccessTokens
  type: entity
  id:
    token:
      type: string
      nullable: false
      length: 2000
  OneToOne:
    user_id:
      targetEntity: User
      joinColumn:
        name: user_id
        referenceColumnName: id
    client_id:
      targetEntity: Client
      joinColumn:
        name: client_id
        referenceColumnName: id
  fields:
    token_scopes:
      type: text
      nullable: false
    grant_type:
      type: string
      nullable: false
      length: 50
    is_revoked:
      type: boolean
      nullable: false
      default: false
    user_id:
      type: integer
      nullable: true
    client_id:
      type: integer
      nullable: false
    expire_at:
      type: integer
      length: 20
      nullable: false
    created_at:
      type: integer
      length: 20
      nullable: false
    updated_at:
      type: integer
      length: 20
      nullable: true
