sonrac\Auth\Entity\AuthCode:
  type: entity
  repostitoryClass: sonrac\Auth\Repository\AuthCodes
  table: auth_codes
  id:
    code:
      type: string
      length: 2000
      nullable: false
      generate:
        strategy: UUID
  OneToOne:
    user_id:
      targetEntity: User
      joinColumn:
        name: user_id
        referenceColumnName: id
    client_id:
      targetEntity: Client
      joinColumn:
        name: client_id
        referenceColumnName: id
  fields:
    is_revoked:
      type: boolean
      nullable: false
      default: false
    redirect_uri:
      type: string
      nullable: false
    scopes:
      type: text
      nullable: false
      default: default
    user_id:
      type: integer
      nullabled: false
    client_id:
      type: integer
      nullable: false
    expire_at:
      type: integer
      length: 20
      nullable: false
    created_at:
      type: integer
      length: 20
      nullable: false
    updated_at:
      type: integer
      length: 20
      nullable: false
