sonrac\Auth\Entity\Client:
  table: clients
  repositoryClass: sonrac\Repository\Clients
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: auto
  OneToOne:
    user_id:
      targetEntity: User
      joinColumn:
        name: user_id
        referenceColumnName: id
  fields:
    name:
      type: string
      nullable: false
      uniqueItems: true
      length: 255
    secret:
      type: text
      nullable: false
    allowed_grant_types:
      type: text
      nullable: false
    redirect_uris:
      type: text
      nullable: true
    user_id:
      type: integer
      nullable: true
    created_at:
      type: integer
      length: 20
      nullable: false
    updated_at:
      type: integer
      length: 20
      nullable: true
