sonrac\Auth\Entity\Client:
  table: clients
  repositoryClass: sonrac\Repository\Clients
  type: entity
  id:
    name:
      type: string
      nullable: false
      uniqueItems: true
      length: 255
  OneToOne:
    user_id:
      targetEntity: User
      joinColumn:
        name: user_id
        referenceColumnName: id
  fields:
    description:
      type: string
      nullable: false
      default: ''
      length: 2000
    secret:
      type: string
      nullable: false
      length: 2000
    allowed_grant_types:
      type: json_array
      nullable: false
    redirect_uris:
      type: json_array
      nullable: true
    user_id:
      type: integer
      nullable: true
    created_at:
      type: integer
      length: 20
      nullable: false
    updated_at:
      type: integer
      length: 20
      nullable: true
